### ISSUE TITLE
Proposiciones logicas 

### ISSUE THREAD

**Issue by irwingsael** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-irwingsael#1]
[INSTITUTO TECNOLÓGICO NACIONAL DE MÉXICO matematicas discretas.pdf](https://github.com/user-attachments/files/17447610/INSTITUTO.TECNOLOGICO.NACIONAL.DE.MEXICO.matematicas.discretas.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
